name: Test and Merge to Main

on:
  pull_request:
    branches:
      - 'main'
 

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Approve Pull Request
        uses: "peter-evans/approve-pull-request@v2"
        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           number: $ {{ github.event.number }}  
           if: ${{ needs.testing.result == 'success'}}

      - name: Merge Pull Request
        uses: "peter-evans/merge-pull-request@v1"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.number }}
          merge-method: squash
          commit-message: "Merge pull request #${{ github.event.number }} from ${GITHUB_REPOSITORY}}/${{ github.head_ref }}"
          if: ${{ needs.testing.result == 'success'}}
          